use-driver: mysql # 使用 mysql or sqlite
mysql:
  master:
    user: root
    password: mysql123
    host: 127.0.0.1
    port: 3306
    database: ucenter
    charset: utf8mb4
redis:
  master:
    host: localhost
    port: 6379
    password:
    database: 0

