basePath: /
definitions:
  datamodels.User:
    properties:
      account:
        description: 帐号
        type: string
      create_time:
        readOnly: true
        type: string
      deleted:
        description: 删除标志1=是，0=否
        type: integer
      disabled:
        description: 禁用状态1=是，0=否
        type: integer
      expired:
        description: 有效期0=永久，unix时间戳
        type: integer
      id:
        example: 1
        type: integer
      nickname:
        description: 昵称
        type: string
      phone:
        type: string
      update_time:
        readOnly: true
        type: string
      uuid:
        example: 5bbc-4ala-3dja-1djs-0aja
        type: string
    type: object
  errors.Errors:
    properties:
      errCode:
        example: 4000000
        type: integer
      message:
        type: string
    type: object
  parameter.Page:
    properties:
      page:
        description: 页码
        type: integer
      size:
        description: 每页条数
        type: integer
    type: object
  parameter.Password:
    properties:
      id:
        description: 用户id
        type: integer
      password:
        description: 密码
        type: string
    required:
    - id
    - password
    type: object
  parameter.User:
    properties:
      account:
        description: 帐号
        type: string
      deleted:
        default: 0
        description: 删除标志1=是，0=否
        type: integer
      disabled:
        default: 0
        description: 禁用状态1=是，0=否
        type: integer
      expired:
        default: 0
        description: 有效期0=永久，unix时间戳
        type: integer
      nickname:
        description: 昵称
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - account
    - nickname
    - password
    type: object
  parameter.UserDeleted:
    properties:
      deleted:
        description: 删除标志0=否，1=是
        type: string
      id:
        description: 用户id
        type: integer
    required:
    - deleted
    - id
    type: object
  parameter.UserDisabled:
    properties:
      disabled:
        description: 禁用标志0=否，1=是
        type: string
      id:
        description: 用户id
        type: integer
    required:
    - disabled
    - id
    type: object
  vo.User:
    properties:
      account:
        description: 帐号
        type: string
      create_time:
        readOnly: true
        type: string
      deleted:
        description: 删除标志1=是，0=否
        type: integer
      disabled:
        description: 禁用状态1=是，0=否
        type: integer
      disabledName:
        example: 已禁用
        type: string
      expired:
        description: 有效期0=永久，unix时间戳
        type: integer
      id:
        example: 1
        type: integer
      nickname:
        description: 昵称
        type: string
      phone:
        type: string
      update_time:
        readOnly: true
        type: string
      uuid:
        example: 5bbc-4ala-3dja-1djs-0aja
        type: string
    type: object
  vo.UserVO:
    properties:
      data:
        description: 每页数据
        items:
          $ref: '#/definitions/vo.User'
        type: array
      page:
        description: 当前页数
        type: integer
      size:
        description: 每页条数
        type: integer
      totalPage:
        description: 总页数
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: peng.yu@yibuyiyin.com
    name: API Support
    url: http://www.yibuyiyin.com/support
  description: 用户中心接口
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://www.yibuyiyin.com/terms/
  title: ucenter api
  version: "1.0"
paths:
  /users:
    delete:
      consumes:
      - application/json
      description: 删除用户信息
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.UserDeleted'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      security:
      - token:
        - read
      summary: 删除用户信息
      tags:
      - 用户管理
    get:
      consumes:
      - application/json
      description: 通过用户ID获取用户信息
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/datamodels.User'
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      security:
      - token:
        - read
      summary: 获取用户信息
      tags:
      - 用户管理
    post:
      consumes:
      - application/json
      description: 创建用户信息
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.User'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/datamodels.User'
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      security:
      - token:
        - read
      summary: 创建用户信息
      tags:
      - 用户管理
    put:
      consumes:
      - application/json
      description: 更新用户信息
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.User'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/datamodels.User'
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      security:
      - token:
        - read
      summary: 更新用户信息
      tags:
      - 用户管理
  /users/byuuid:
    get:
      consumes:
      - application/json
      description: 通过用户uuid获取用户信息
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/datamodels.User'
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      security:
      - token:
        - read
      summary: 获取用户信息
      tags:
      - 用户管理
  /users/disabled:
    put:
      consumes:
      - application/json
      description: 设置用户禁用状态
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.UserDisabled'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      security:
      - token:
        - read
      summary: 设置用户禁用状态
      tags:
      - 用户管理
  /users/list:
    get:
      consumes:
      - application/json
      description: 获取全部用户分页列表
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.Page'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/vo.UserVO'
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      security:
      - token:
        - read
      summary: 获取用户分页列表
      tags:
      - 用户管理
  /users/password:
    put:
      consumes:
      - application/json
      description: 修改登陆用户密码
      parameters:
      - description: request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.Password'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/errors.Errors'
      security:
      - token:
        - read
      summary: 修改登陆用户密码
      tags:
      - 用户管理
swagger: "2.0"
