basePath: /
definitions:
  datamodels.User:
    properties:
      account:
        description: 帐号
        type: string
      create_time:
        readOnly: true
        type: string
      deleted:
        default: 0
        description: 删除标志1=是，0=否
        type: integer
      disabled:
        default: 0
        description: 禁用状态1=是，0=否
        type: integer
      expired:
        default: 0
        description: 有效期0=永久，unix时间戳
        type: integer
      id:
        example: 1
        readOnly: true
        type: integer
      nickname:
        description: 昵称
        type: string
      password:
        type: string
      phone:
        type: string
      update_time:
        readOnly: true
        type: string
      uuid:
        example: 5bbc-4ala-3dja-1djs-0aja
        readOnly: true
        type: string
    required:
    - account
    - nickname
    - password
    type: object
  errors.Errors:
    properties:
      errorCode:
        type: integer
      errorMessage:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: peng.yu@yibuyiyin.com
    name: API Support
    url: http://www.yibuyiyin.com/support
  description: 用户中心接口
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://www.yibuyiyin.com/terms/
  title: ucenter api
  version: "1.0"
paths:
  /users:
    delete:
      consumes:
      - application/json
      description: 删除用户
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户管理
    get:
      consumes:
      - application/json
      description: 通过用户ID获取用户信息
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/datamodels.User'
      summary: 获取用户信息
      tags:
      - 用户管理
    post:
      consumes:
      - application/json
      description: 创建用户
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/datamodels.User'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/datamodels.User'
      summary: 创建用户
      tags:
      - 用户管理
    put:
      consumes:
      - application/json
      description: 更新用户
      parameters:
      - description: 昵称
        in: query
        name: nickname
        required: true
        type: string
      - description: 手机号
        in: query
        name: phone
        type: string
      - description: 有效期，0=永久/指定过期时间，默认:0
        in: query
        name: expired
        type: string
      - description: 是否禁用状态1=是;0=否，默认:否
        in: query
        name: disabled
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/datamodels.User'
      summary: 更新用户
      tags:
      - 用户管理
  /users/disabled:
    put:
      consumes:
      - application/json
      description: 设置用户禁用状态
      parameters:
      - description: 用户id
        in: query
        name: id
        required: true
        type: integer
      - description: 0=启用；1=禁用
        in: query
        name: disabled
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 设置用户禁用状态
      tags:
      - 用户管理
  /users/password:
    put:
      consumes:
      - application/json
      description: 修改当前用户密码
      parameters:
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 修改当前用户密码
      tags:
      - 用户管理
  /users/uuid:
    get:
      consumes:
      - application/json
      description: 通过用户ID获取用户信息
      parameters:
      - description: 用户uuid
        in: query
        name: uuid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: error message
          schema:
            $ref: '#/definitions/errors.Errors'
      summary: 获取用户信息
      tags:
      - 用户管理
swagger: "2.0"
